"""sync orm schema

Revision ID: ba36df83378f
Revises: 
Create Date: 2026-03-21 08:03:52.040356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba36df83378f'
down_revision = None
branch_labels = None
depends_on = None


def _drop_table_if_exists(table_name: str) -> None:
    op.execute(sa.text(f"DROP TABLE IF EXISTS `{table_name}`"))


def _normalize_nullable_unique_column(table_name: str, column_name: str) -> None:
    op.execute(
        sa.text(
            f"""
            UPDATE `{table_name}`
            SET `{column_name}` = NULL
            WHERE `{column_name}` IS NOT NULL
              AND TRIM(`{column_name}`) = ''
            """
        )
    )
    op.execute(
        sa.text(
            f"""
            UPDATE `{table_name}` AS target
            JOIN (
                SELECT `{column_name}`, MIN(`id`) AS keep_id
                FROM `{table_name}`
                WHERE `{column_name}` IS NOT NULL
                GROUP BY `{column_name}`
                HAVING COUNT(*) > 1
            ) AS duplicates
                ON target.`{column_name}` = duplicates.`{column_name}`
               AND target.`id` <> duplicates.`keep_id`
            SET target.`{column_name}` = NULL
            """
        )
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("SET FOREIGN_KEY_CHECKS=0"))
    _drop_table_if_exists('finance_report')
    _drop_table_if_exists('recent_favorite')
    _drop_table_if_exists('order_items')
    _drop_table_if_exists('music_resource')
    _drop_table_if_exists('finance_pos_save')
    _drop_table_if_exists('finance_income_record')
    _drop_table_if_exists('finance_expenses_record')
    _drop_table_if_exists('orders')
    _drop_table_if_exists('music_data')
    _drop_table_if_exists('music_version')
    _drop_table_if_exists('music_album')
    _drop_table_if_exists('user_log')
    _drop_table_if_exists('stock_detail')
    _drop_table_if_exists('finance_table')
    _drop_table_if_exists('item_form_data')
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('album_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'artist', ['artist_id'], ['id'])

    with op.batch_alter_table('album_files', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.CHAR(length=8),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('uix_folder_file'))

    with op.batch_alter_table('department_permission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_department_permission_department'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_department_permission_permission'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_data', schema=None) as batch_op:
        batch_op.drop_column('brochure')
        batch_op.drop_column('organizer')

    with op.batch_alter_table('event_flow_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_flow_creator_id'))
        batch_op.drop_index(batch_op.f('idx_event_flow_event_id'))
        batch_op.drop_index(batch_op.f('idx_event_flow_handler_id'))
        batch_op.drop_index(batch_op.f('idx_event_flow_minutes'))
        batch_op.drop_index(batch_op.f('idx_event_flow_no'))
        batch_op.create_index(batch_op.f('ix_event_flow_data_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_flow_data_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_flow_data_handler_id'), ['handler_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_flow_data_minutes'), ['minutes'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_flow_data_no'), ['no'], unique=False)

    with op.batch_alter_table('event_organizer', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('music_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_index(batch_op.f('user_music_unique'))
        batch_op.drop_constraint(batch_op.f('favorite_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('favorite_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'music', ['music_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])

    with op.batch_alter_table('file_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_history_file'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_history_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])

    with op.batch_alter_table('file_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_permission_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_permission_file'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_permission_dept'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])

    with op.batch_alter_table('file_trash', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trash_owner'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_trash_deleted_by'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_trash_file'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['deleted_by'], ['id'])
        batch_op.create_foreign_key(None, 'user_data', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_files_owner'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['owner_id'], ['id'])

    with op.batch_alter_table('lamp', schema=None) as batch_op:
        batch_op.alter_column('registration_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='对应 lamp_registration.id',
               existing_nullable=False)
        batch_op.alter_column('lamp_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='供灯类型：lamp_88 / lamp_168',
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='单盏灯金额',
               existing_nullable=False)
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='备注（祈福说明）',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_lamp_registration'))
        batch_op.create_index(batch_op.f('ix_lamp_registration_id'), ['registration_id'], unique=False)
        batch_op.create_foreign_key(None, 'lamp_registration', ['registration_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_table_comment(
        existing_comment='供灯明细（一单多灯）'
    )

    with op.batch_alter_table('lamp_payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='收款金额',
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='收款方式：cash / transfer / tng',
               existing_nullable=True)
        batch_op.alter_column('paid_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='付款时间',
               existing_nullable=True)
        batch_op.alter_column('note',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_lamp_payment_phone'))
        batch_op.create_index(batch_op.f('ix_lamp_payment_submitter_id'), ['submitter_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='点灯供佛收款记录'
    )

    with op.batch_alter_table('lamp_payment_registration', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('registration_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_lpr_payment_id'))
        batch_op.drop_index(batch_op.f('idx_lpr_registration_id'))
        batch_op.drop_constraint(batch_op.f('fk_lpr_registration'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_lpr_payment'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lamp_payment', ['payment_id'], ['id'])
        batch_op.create_foreign_key(None, 'lamp_registration', ['registration_id'], ['id'])

    with op.batch_alter_table('lamp_registration', schema=None) as batch_op:
        batch_op.alter_column('devotee_name',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='祈福者姓名',
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='地址',
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='总金额',
               existing_nullable=False)
        batch_op.alter_column('serial_no',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='编号',
               existing_nullable=True)
        batch_op.alter_column('receipt_no',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='收据号码',
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='收款日期',
               existing_nullable=True)
        batch_op.alter_column('cashier_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='收款人',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='状态：submitted / paid / canceled',
               existing_nullable=False,
               existing_server_default=sa.text("'submitted'"))
        batch_op.drop_index(batch_op.f('idx_lamp_reg_created'))
        batch_op.drop_index(batch_op.f('idx_lamp_reg_receipt'))
        batch_op.drop_index(batch_op.f('idx_lamp_reg_serial'))
        batch_op.drop_index(batch_op.f('idx_lamp_registration_phone'))
        batch_op.drop_table_comment(
        existing_comment='新春点灯供佛祈福报名表'
    )
        batch_op.drop_column('phone_home')

    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('music_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('music_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'artist', ['artist_id'], ['id'])
        batch_op.create_foreign_key(None, 'album', ['album_id'], ['id'])

    with op.batch_alter_table('music_queue', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('fk_music_queue_current_music'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_music_queue_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'music', ['current_music_id'], ['id'])

    with op.batch_alter_table('play_history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('music_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('play_history_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('play_history_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'music', ['music_id'], ['id'])

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('playlist_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])

    with op.batch_alter_table('playlist_music', schema=None) as batch_op:
        batch_op.alter_column('playlist_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('music_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('playlist_music_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('playlist_music_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'playlist', ['playlist_id'], ['id'])
        batch_op.create_foreign_key(None, 'music', ['music_id'], ['id'])

    with op.batch_alter_table('playlist_state', schema=None) as batch_op:
        batch_op.alter_column('playback_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('fk_playlist_state_current_music'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_playlist_state_playlist'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_playlist_state_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'playlist', ['active_playlist_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'music', ['current_music_id'], ['id'])

    with op.batch_alter_table('regis_form', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('regis_form_event', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('regis_form_extra_field_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_field_config_form'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'regis_form', ['regis_form_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('regis_form_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_form_member_member'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_form_member_form'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'regis_member', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'regis_form', ['form_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('regis_member_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_member_data_member'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'regis_member', ['member_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('regis_member_field_value', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_field_value_config'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_field_value_member_data'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'regis_member_data', ['regis_member_data_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'regis_form_extra_field_config', ['field_config_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('field_type')

    with op.batch_alter_table('regis_payment', schema=None) as batch_op:
        batch_op.alter_column('regis_form_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('payment_mode',
               existing_type=mysql.ENUM('bank', 'QR', 'cash'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_nric'))
        batch_op.create_foreign_key(None, 'regis_form', ['regis_form_id'], ['id'])

    with op.batch_alter_table('registration_fee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_registration_fee_form'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'regis_form', ['regis_form_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reimbursement_approver_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_rad_dep_id'))
        batch_op.drop_index(batch_op.f('idx_rad_request_id'))
        batch_op.drop_index(batch_op.f('idx_rad_user_id'))
        batch_op.create_index(batch_op.f('ix_reimbursement_approver_data_dep_id'), ['dep_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_approver_data_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_approver_data_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('reimbursement_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ra_request_id'))
        batch_op.drop_index(batch_op.f('idx_ra_uploader_user_id'))
        batch_op.create_index(batch_op.f('ix_reimbursement_attachment_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_attachment_uploader_user_id'), ['uploader_user_id'], unique=False)

    with op.batch_alter_table('reimbursement_request', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('is_locked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_applicant_user_id'))
        batch_op.drop_index(batch_op.f('idx_department_id'))
        batch_op.drop_index(batch_op.f('idx_event_id'))
        batch_op.drop_index(batch_op.f('public_token'))
        batch_op.create_index(batch_op.f('ix_reimbursement_request_applicant_user_id'), ['applicant_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_request_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_request_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_request_public_token'), ['public_token'], unique=True)
        batch_op.drop_column('payment_sign_json_data')

    with op.batch_alter_table('share_public', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_share_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_share_file'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_data', ['created_user'], ['id'])

    _normalize_nullable_unique_column('user_data', 'phone')
    _normalize_nullable_unique_column('user_data', 'email')
    _normalize_nullable_unique_column('user_data', 'username')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_constraint(batch_op.f('fk_user_created_by'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['created_by'], ['id'])
        batch_op.drop_column('dipartment')
        batch_op.drop_column('department')
        batch_op.drop_column('dipartment_class')
        batch_op.drop_column('permissions')
        batch_op.drop_column('position')

    with op.batch_alter_table('user_department', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_department_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_department_department'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    with op.batch_alter_table('view_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_view_file'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_view_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])

    op.execute(sa.text("SET FOREIGN_KEY_CHECKS=1"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_view_user'), 'user_data', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_view_file'), 'files', ['file_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_department_department'), 'department', ['department_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user_department_user'), 'user_data', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('permissions', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), server_default=sa.text('json_array()'), nullable=True))
        batch_op.add_column(sa.Column('dipartment_class', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('department', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), server_default=sa.text('json_array()'), nullable=True))
        batch_op.add_column(sa.Column('dipartment', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_created_by'), 'user_data', ['created_by'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('share_public', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_share_file'), 'files', ['file_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_share_user'), 'user_data', ['created_user'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reimbursement_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_sign_json_data', mysql.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reimbursement_request_public_token'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_request_event_id'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_request_department_id'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_request_applicant_user_id'))
        batch_op.create_index(batch_op.f('public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('idx_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_applicant_user_id'), ['applicant_user_id'], unique=False)
        batch_op.alter_column('is_locked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('reimbursement_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reimbursement_attachment_uploader_user_id'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_attachment_request_id'))
        batch_op.create_index(batch_op.f('idx_ra_uploader_user_id'), ['uploader_user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ra_request_id'), ['request_id'], unique=False)

    with op.batch_alter_table('reimbursement_approver_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reimbursement_approver_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_approver_data_request_id'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_approver_data_dep_id'))
        batch_op.create_index(batch_op.f('idx_rad_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_rad_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_rad_dep_id'), ['dep_id'], unique=False)

    with op.batch_alter_table('registration_fee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_registration_fee_form'), 'regis_form', ['regis_form_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('regis_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_nric'), ['nric'], unique=False)
        batch_op.alter_column('payment_mode',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('bank', 'QR', 'cash'),
               existing_nullable=False)
        batch_op.alter_column('regis_form_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('regis_member_field_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_field_value_member_data'), 'regis_member_data', ['regis_member_data_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_field_value_config'), 'regis_form_extra_field_config', ['field_config_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('regis_member_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_member_data_member'), 'regis_member', ['member_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('regis_form_member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_form_member_form'), 'regis_form', ['form_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_form_member_member'), 'regis_member', ['member_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('regis_form_extra_field_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_field_config_form'), 'regis_form', ['regis_form_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('regis_form_event', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('form_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('regis_form', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('playlist_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_playlist_state_user'), 'user_data', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_playlist_state_playlist'), 'playlist', ['active_playlist_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_playlist_state_current_music'), 'music', ['current_music_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('playback_time',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('playlist_music', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('playlist_music_ibfk_1'), 'playlist', ['playlist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('playlist_music_ibfk_2'), 'music', ['music_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('music_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('playlist_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('playlist_ibfk_1'), 'user_data', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('play_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('play_history_ibfk_2'), 'music', ['music_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('play_history_ibfk_1'), 'user_data', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('music_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('music_queue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_music_queue_user'), 'user_data', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_music_queue_current_music'), 'music', ['current_music_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('music_ibfk_1'), 'album', ['album_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('music_ibfk_2'), 'artist', ['artist_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('lamp_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_home', mysql.VARCHAR(length=50), nullable=True, comment='电话（住家）'))
        batch_op.create_table_comment(
        '新春点灯供佛祈福报名表',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_lamp_registration_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('idx_lamp_reg_serial'), ['serial_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_lamp_reg_receipt'), ['receipt_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_lamp_reg_created'), ['created_at'], unique=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=30),
               comment='状态：submitted / paid / canceled',
               existing_nullable=False,
               existing_server_default=sa.text("'submitted'"))
        batch_op.alter_column('cashier_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='收款人',
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.DATE(),
               comment='收款日期',
               existing_nullable=True)
        batch_op.alter_column('receipt_no',
               existing_type=mysql.VARCHAR(length=50),
               comment='收据号码',
               existing_nullable=True)
        batch_op.alter_column('serial_no',
               existing_type=mysql.VARCHAR(length=50),
               comment='编号',
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='总金额',
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.TEXT(),
               comment='地址',
               existing_nullable=True)
        batch_op.alter_column('devotee_name',
               existing_type=mysql.VARCHAR(length=200),
               comment='祈福者姓名',
               existing_nullable=False)

    with op.batch_alter_table('lamp_payment_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lpr_payment'), 'lamp_payment', ['payment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_lpr_registration'), 'lamp_registration', ['registration_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_lpr_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_lpr_payment_id'), ['payment_id'], unique=False)
        batch_op.alter_column('registration_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('payment_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    with op.batch_alter_table('lamp_payment', schema=None) as batch_op:
        batch_op.create_table_comment(
        '点灯供佛收款记录',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_lamp_payment_submitter_id'))
        batch_op.create_index(batch_op.f('idx_lamp_payment_phone'), ['phone'], unique=False)
        batch_op.alter_column('note',
               existing_type=mysql.TEXT(),
               comment='备注',
               existing_nullable=True)
        batch_op.alter_column('paid_at',
               existing_type=mysql.DATETIME(),
               comment='付款时间',
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=mysql.VARCHAR(length=30),
               comment='收款方式：cash / transfer / tng',
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='收款金额',
               existing_nullable=False)

    with op.batch_alter_table('lamp', schema=None) as batch_op:
        batch_op.create_table_comment(
        '供灯明细（一单多灯）',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lamp_registration_id'))
        batch_op.create_index(batch_op.f('idx_lamp_registration'), ['registration_id'], unique=False)
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=200),
               comment='备注（祈福说明）',
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='单盏灯金额',
               existing_nullable=False)
        batch_op.alter_column('lamp_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='供灯类型：lamp_88 / lamp_168',
               existing_nullable=False)
        batch_op.alter_column('registration_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='对应 lamp_registration.id',
               existing_nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_files_owner'), 'user_data', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('file_trash', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trash_file'), 'files', ['file_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_trash_deleted_by'), 'user_data', ['deleted_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_trash_owner'), 'user_data', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('file_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_permission_dept'), 'department', ['department_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_permission_file'), 'files', ['file_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_permission_user'), 'user_data', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('file_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_history_user'), 'user_data', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_history_file'), 'files', ['file_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorite_ibfk_2'), 'music', ['music_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('favorite_ibfk_1'), 'user_data', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('user_music_unique'), ['user_id', 'music_id'], unique=True)
        batch_op.alter_column('music_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('event_organizer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('event_flow_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_flow_data_no'))
        batch_op.drop_index(batch_op.f('ix_event_flow_data_minutes'))
        batch_op.drop_index(batch_op.f('ix_event_flow_data_handler_id'))
        batch_op.drop_index(batch_op.f('ix_event_flow_data_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_flow_data_creator_id'))
        batch_op.create_index(batch_op.f('idx_event_flow_no'), ['event_id', 'no'], unique=False)
        batch_op.create_index(batch_op.f('idx_event_flow_minutes'), ['minutes'], unique=False)
        batch_op.create_index(batch_op.f('idx_event_flow_handler_id'), ['handler_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_event_flow_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_event_flow_creator_id'), ['creator_id'], unique=False)

    with op.batch_alter_table('event_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('brochure', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))

    with op.batch_alter_table('department_permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_department_permission_permission'), 'permission', ['permission_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_department_permission_department'), 'department', ['department_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('album_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uix_folder_file'), ['folder_name', 'file_name'], unique=True)
        batch_op.alter_column('date',
               existing_type=sa.String(length=8),
               type_=mysql.CHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('album_ibfk_1'), 'artist', ['artist_id'], ['id'], ondelete='SET NULL')

    op.create_table('item_form_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('field_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('field_value', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['order_items.id'], name=op.f('item_form_data_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('finance_table',
    sa.Column('table_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('table_user', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('datetime', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('edit_datetime', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.Column('remove_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link_point', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('view_permissions', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('mount_user', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('public', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=32), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('is_locked', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('table_id'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('stock_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('datetime', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unit_price', mysql.FLOAT(), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('product_name_cn', mysql.VARCHAR(length=100), server_default=sa.text("'未知商品'"), nullable=False),
    sa.Column('img', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('required_class', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_class', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('args', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('kwargs', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('form_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('json_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('music_album',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('theme_song_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['theme_song_id'], ['music_data.id'], name=op.f('fk_music_album_theme_song')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('music_version',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('version_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('song_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('default_resource_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['default_resource_id'], ['music_resource.id'], name=op.f('fk_music_version_default_resource')),
    sa.ForeignKeyConstraint(['song_id'], ['music_data.id'], name=op.f('music_version_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('music_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('artist', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('album_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('default_version_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['music_album.id'], name=op.f('music_data_ibfk_1')),
    sa.ForeignKeyConstraint(['default_version_id'], ['music_version.id'], name=op.f('fk_music_data_default_version')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', mysql.TIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('customer_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('member_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('full_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('finance_expenses_record',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('table_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('datetime', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('img_path', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('unit_price', mysql.FLOAT(), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('item_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('detail', mysql.TEXT(), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['finance_table.table_id'], name=op.f('finance_expenses_record_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['finance_table.table_id'], name=op.f('fk_expense_table')),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('finance_income_record',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('table_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('datetime', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('unit_price', mysql.FLOAT(), nullable=False),
    sa.Column('detail', mysql.TEXT(), nullable=True),
    sa.Column('confirmed', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('img_path', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['finance_table.table_id'], name=op.f('finance_income_record_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['finance_table.table_id'], name=op.f('fk_income_table')),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('finance_pos_save',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('table_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('save_product_json', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('music_resource',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('version_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('resource_type', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['music_version.id'], name=op.f('music_resource_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('item_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('line_id', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recent_favorite',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('song_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('added_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['music_data.id'], name=op.f('recent_favorite_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('finance_report',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('event_code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('table_link_id', mysql.TEXT(), nullable=True),
    sa.Column('report_name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
