"""add asset inventory module

Revision ID: c03c0cd76f66
Revises: de06fbbf93c4
Create Date: 2026-04-24 10:02:40.223352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03c0cd76f66'
down_revision = 'de06fbbf93c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_item_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_item_status'), ['status'], unique=False)

    op.create_table('asset_sub_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['asset_item.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_sub_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_sub_item_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_sub_item_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_sub_item_size'), ['size'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_sub_item_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_sub_item_status'), ['status'], unique=False)

    op.create_table('asset_warehouse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['user_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('asset_warehouse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_warehouse_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_warehouse_manager_user_id'), ['manager_user_id'], unique=False)

    op.create_table('asset_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('sub_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sub_item_id'], ['asset_sub_item.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['asset_warehouse.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'sub_item_id', name='uq_asset_inventory_warehouse_sub_item')
    )
    with op.batch_alter_table('asset_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_inventory_sub_item_id'), ['sub_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_inventory_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('asset_stock_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_no', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('target_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('requester_user_id', sa.Integer(), nullable=True),
    sa.Column('handler_user_id', sa.Integer(), nullable=True),
    sa.Column('taken_by_user_id', sa.Integer(), nullable=True),
    sa.Column('taken_by_name', sa.String(length=120), nullable=True),
    sa.Column('destination_type', sa.String(length=30), nullable=True),
    sa.Column('destination_text', sa.String(length=255), nullable=True),
    sa.Column('counterparty_name', sa.String(length=160), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(length=80), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('invoice_file_path', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['event_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handler_user_id'], ['user_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['user_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['asset_warehouse.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['taken_by_user_id'], ['user_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_warehouse_id'], ['asset_warehouse.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_stock_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_stock_document_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_document_no'), ['document_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_handler_user_id'), ['handler_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_requester_user_id'), ['requester_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_source_warehouse_id'), ['source_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_taken_by_user_id'), ['taken_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_target_warehouse_id'), ['target_warehouse_id'], unique=False)

    op.create_table('asset_stock_document_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('sub_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['asset_stock_document.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_item_id'], ['asset_sub_item.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_stock_document_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_stock_document_line_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_document_line_sub_item_id'), ['sub_item_id'], unique=False)

    op.create_table('asset_stock_movement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_line_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('sub_item_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('taken_by_user_id', sa.Integer(), nullable=True),
    sa.Column('destination_text', sa.String(length=255), nullable=True),
    sa.Column('invoice_no', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['asset_stock_document.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_line_id'], ['asset_stock_document_line.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_item_id'], ['asset_sub_item.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['taken_by_user_id'], ['user_data.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['asset_warehouse.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_stock_movement_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_movement_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_movement_document_line_id'), ['document_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_movement_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_movement_sub_item_id'), ['sub_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_movement_taken_by_user_id'), ['taken_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stock_movement_warehouse_id'), ['warehouse_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_stock_movement_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_movement_taken_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_movement_sub_item_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_movement_movement_type'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_movement_document_line_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_movement_document_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_movement_created_by'))

    op.drop_table('asset_stock_movement')
    with op.batch_alter_table('asset_stock_document_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_line_sub_item_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_line_document_id'))

    op.drop_table('asset_stock_document_line')
    with op.batch_alter_table('asset_stock_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_target_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_taken_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_status'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_source_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_requester_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_handler_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_event_id'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_document_type'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_document_no'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_created_by'))
        batch_op.drop_index(batch_op.f('ix_asset_stock_document_approved_by'))

    op.drop_table('asset_stock_document')
    with op.batch_alter_table('asset_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_inventory_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_asset_inventory_sub_item_id'))

    op.drop_table('asset_inventory')
    with op.batch_alter_table('asset_warehouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_warehouse_manager_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_warehouse_code'))

    op.drop_table('asset_warehouse')
    with op.batch_alter_table('asset_sub_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_sub_item_status'))
        batch_op.drop_index(batch_op.f('ix_asset_sub_item_sku'))
        batch_op.drop_index(batch_op.f('ix_asset_sub_item_size'))
        batch_op.drop_index(batch_op.f('ix_asset_sub_item_item_id'))
        batch_op.drop_index(batch_op.f('ix_asset_sub_item_barcode'))

    op.drop_table('asset_sub_item')
    with op.batch_alter_table('asset_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_item_status'))
        batch_op.drop_index(batch_op.f('ix_asset_item_code'))

    op.drop_table('asset_item')
    # ### end Alembic commands ###
