"""add other_remark to registration forms and member data

Revision ID: 2ba482fbd8a7
Revises: d9b6a4c2f1e7
Create Date: 2026-04-10 06:30:15.968583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba482fbd8a7'
down_revision = 'd9b6a4c2f1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regis_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_remark', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('regis_member_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_remark', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regis_member_data', schema=None) as batch_op:
        batch_op.drop_column('other_remark')

    with op.batch_alter_table('regis_form', schema=None) as batch_op:
        batch_op.drop_column('other_remark')

    # ### end Alembic commands ###
